### ISSUE TITLE
Hyphenated project names make things weird.

### ISSUE THREAD

**Issue by pote** [tonchis/tmuxify#2]
So I have a lot of projects that have multiple components, and sometimes I name the directories `app` and  `app-web`, the thing is: whenever I run tmuxify in `app-web` and the `app` session is alive it loads that one instead of `app-web`.

I think this is due to the `| tr . -` used when getting the session name, but I'm not sure why it's there, so I wanted to bring it up before submitting a patch.

**Comment by tonchis** [comment]
@pote interesting. I'll look into this, but I think it's a prefix problem, not specific to hyphens.

**Comment by pote** [comment]
Could be! I haven't looked into it too deeply.

**Comment by tonchis** [comment]
Fixed by #3 and available in [v1.2.1](https://github.com/tonchis/tmuxify/releases/v1.2.1)
